spring:
  application:
    name: telega
  datasource:
    url: jdbc:postgresql://localhost:5432/tg_bot
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}

logging:
  level:
    test: DEBUG